### ISSUE TITLE
Typo causes UI freeze

### ISSUE THREAD

**Issue by BobombNik80** [jcsato/sato_additional_equipment_mod#1]
![BBsatolog](https://user-images.githubusercontent.com/112902251/188506318-32ef10c0-9f9e-4920-a339-3f50112e3a9c.PNG)

- Failed to load script file "scripts/items/weapons/barbarians/two_handed_spikce_mace.(nut/cnut)". Reason: File not found.
- Failed to create new instance from "scripts/items/weapons/barbarians/two_handed_spikce_mace". Reason: Script not found.
- the index 'isItemType' does not exist

I went in and updated the line to the correct spelling (in my own copy of the mod) and it allowed the current save to continue working as normal. Should be "spiked" instead of "spikce".

**Comment by jcsato** [comment]
Thanks for reporting! This is actually an [expanded markets](https://github.com/jcsato/sato_expanded_markets_mod) bug - I push a fix in that repo as soon as I get a chance.

**Comment by BobombNik80** [comment]
> Thanks for reporting! This is actually an [expanded markets](https://github.com/jcsato/sato_expanded_markets_mod) bug - I push a fix in that repo as soon as I get a chance.

Oh, I must have clicked on the wrong heading by accident - apologies! Glad to be of some help - appreciate your work. :)

**Comment by jcsato** [comment]
Resolved by https://github.com/jcsato/sato_expanded_markets_mod/releases/tag/v1.2
